### ISSUE TITLE
DelegationToken not support on Kafka 1.x.x

### ISSUE THREAD

**Issue by fsbaraglia** [simplesteph/kafka-security-manager#40]
Hi,
I found a problem using kafka-security-manager release latest or v03-release .
As soon you start the container, also using the default configuration to do not make any changes in zookeeper, the kafka-security-manager is creating a key automatically in /kafka-acl/DelegationToken, after kafka-acls is concerning about the DelegationToken key in zookeeper, as far as I know this feature "DelegationToken" can be used only in the kafka 2, do you have also figured out this problem ?
Thank you,
Frank

**Comment by simplesteph** [comment]
What's the log you're getting ? Can you create a docker compose file to reproduce the issue ?

I'm not sure KSM would be backward compatible so you would have to use a KSM version that corresponds to your Kafka version

**Comment by fsbaraglia** [comment]
this is the content of zookeeper before :
        WatchedEvent state:SyncConnected type:None path:null
        [Group, Cluster, Topic, TransactionalId]
after I run kafka-security-manager:
        WatchedEvent state:SyncConnected type:None path:null
        [Group, Cluster, Topic, TransactionalId, DelegationToken]

here the failure of kafka-acls run after running kafka-security-manager:
18/12/18 11:23:51 INFO zkclient.ZkClient: zookeeper state changed (SyncConnected)
18/12/18 11:23:51 INFO zkclient.ZkClient: zookeeper state changed (SaslAuthenticated)
18/12/18 11:23:51 INFO zkclient.ZkEventThread: Terminate ZkClient event thread.
18/12/18 11:23:51 INFO zookeeper.ZooKeeper: Session: 0x6767a3945e9e2e71 closed
18/12/18 11:23:51 INFO zookeeper.ClientCnxn: EventThread shut down
Error while executing ACL command: DelegationToken not a valid resourceType name. The valid names are Topic,Group,Cluster,TransactionalId
kafka.common.KafkaException: DelegationToken not a valid resourceType name. The valid names are Topic,Group,Cluster,TransactionalId
        at kafka.security.auth.ResourceType$$anonfun$fromString$1.apply(ResourceType.scala:56)
        at kafka.security.auth.ResourceType$$anonfun$fromString$1.apply(ResourceType.scala:56)
        at scala.Option.getOrElse(Option.scala:121)
        at kafka.security.auth.ResourceType$.fromString(ResourceType.scala:56)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1$$anonfun$apply$mcV$sp$1.apply(SimpleAclAuthorizer.scala:233)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1$$anonfun$apply$mcV$sp$1.apply(SimpleAclAuthorizer.scala:232)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply$mcV$sp(SimpleAclAuthorizer.scala:232)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply(SimpleAclAuthorizer.scala:230)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply(SimpleAclAuthorizer.scala:230)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:217)
        at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:225)
        at kafka.security.auth.SimpleAclAuthorizer.loadCache(SimpleAclAuthorizer.scala:230)
        at kafka.security.auth.SimpleAclAuthorizer.configure(SimpleAclAuthorizer.scala:114)
        at kafka.admin.AclCommand$.withAuthorizer(AclCommand.scala:77)
        at kafka.admin.AclCommand$.kafka$admin$AclCommand$$listAcl(AclCommand.scala:118)
        at kafka.admin.AclCommand$.main(AclCommand.scala:55)
        at kafka.admin.AclCommand.main(AclCommand.scala)

to solve the problem I just remove the entry in zookeeper for /kafka-acl/DelegationToken

**Comment by simplesteph** [comment]
Yes so overall it seems the kafka project is not fully backwards compatible for the security module so I would recommend using a KSM version that's compatible with 1.1. But if the way you did it works then all good !
