### ISSUE TITLE
Unable to use basic auth

### ISSUE THREAD

**Issue by pmcconnell-tc** [simplesteph/kafka-security-manager#51]
I get this exception when trying to use basic auth:

```
[2019-07-02 14:58:26,349] ERROR Refreshing the source failed (AclSynchronizer)
java.io.UnsupportedEncodingException: UTF ​-8
	at java.lang.StringCoding.encode(StringCoding.java:341)
	at java.lang.String.getBytes(String.java:918)
	at com.github.simplesteph.ksm.source.GitHubSourceAcl.$anonfun$refresh$1(GitHubSourceAcl.scala:58)
	at scala.Option.foreach(Option.scala:257)
	at com.github.simplesteph.ksm.source.GitHubSourceAcl.refresh(GitHubSourceAcl.scala:57)
	at com.github.simplesteph.ksm.AclSynchronizer.$anonfun$run$1(AclSynchronizer.scala:76)
	at scala.util.Try$.apply(Try.scala:209)
	at com.github.simplesteph.ksm.AclSynchronizer.run(AclSynchronizer.scala:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Note the space between "UTF" and "-8". I believe there are extraneous characters here:

https://github.com/simplesteph/kafka-security-manager/blob/15f802df04f0837275e67c349e39db5ea348256d/src/main/scala/com/github/simplesteph/ksm/source/GitHubSourceAcl.scala#L58

That line looks reasonable in GitHub, but when I open it in vi it looks like this:

```
val basicB64 = Base64.getEncoder.encodeToString(basic.getBytes("UTF<200c><200b>-8"))
```

I believe that string should just be "UTF-8".

**Comment by simplesteph** [comment]
Odd. Can you please change that line and see if that fixes the issue for you ?

**Comment by RadishTheHut** [comment]
I changed that line and it did fix the issue for me. I've raised PR #52 for it.
