### ISSUE TITLE
Unable to run once

### ISSUE THREAD

**Issue by andriyfedorov** [simplesteph/kafka-security-manager#64]
Hi there,

Application raises java.lang.IllegalArgumentException when refresh.frequency.ms (or KSM_REFRESH_FREQUENCY_MS) is set to "-1".

Error:

```
Exception in thread "main" java.lang.IllegalArgumentException
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:565)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$simplesteph$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:55)
	at com.github.simplesteph.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:13)
	at com.github.simplesteph.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)
```

**Comment by simplesteph** [comment]
weird... can you please submit a PR and a test case for this? Thanks for catching this

**Comment by simplesteph** [comment]
I mean, it's supposed to already catch the "-1":
https://github.com/simplesteph/kafka-security-manager/blob/1f09be97f5b18da2fb071751d81aa7d745c0eab8/src/main/scala/com/github/simplesteph/ksm/KafkaSecurityManager.scala#L57

If you can share your config values and more log that'll be helpful

**Comment by andriyfedorov** [comment]
I think problem is with passing negative value as a parameter. I am using default configuration and just overriding KSM_REFRESH_FREQUENCY_MS to "-1".

Would you be able to test it on your side to confirm that issue exist?

**Comment by andriyfedorov** [comment]
I've tested use of 0 instead of -1 and it appears to be working fine. 
https://github.com/simplesteph/kafka-security-manager/pull/65
