### ISSUE TITLE
Kafka 2.4.1 Support

### ISSUE THREAD

**Issue by CurtisEppel** [simplesteph/kafka-security-manager#84]
Upgrade Kafka Security Manager to be compatible with Kafka 2.4.1.

When running KSM with a cluster using version 2.4.1 I get the following error. The README currently states compatibility with version 2.3.1.
```
[2020-07-08 10:48:46,937] ERROR Exceptions while refreshing ACL source: (AclSynchronizer)
[2020-07-08 10:48:46,939] ERROR refresh exception (ConsoleNotification)
com.github.simplesteph.ksm.parser.CsvParserException: kafka.common.KafkaException: Allow not a valid operation name. The valid names are Read,Write,Create,Delete,Alter,Describe,ClusterAction,AlterConfigs,DescribeConfigs,IdempotentWrite,All
	at com.github.simplesteph.ksm.parser.CsvAclParser$$anonfun$$nestedInanonfun$aclsFromReader$2$1.$anonfun$applyOrElse$1(CsvAclParser.scala:85)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.simplesteph.ksm.parser.CsvAclParser$$anonfun$$nestedInanonfun$aclsFromReader$2$1.applyOrElse(CsvAclParser.scala:85)
	at com.github.simplesteph.ksm.parser.CsvAclParser$$anonfun$$nestedInanonfun$aclsFromReader$2$1.applyOrElse(CsvAclParser.scala:84)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at com.github.simplesteph.ksm.parser.CsvAclParser.$anonfun$aclsFromReader$2(CsvAclParser.scala:84)
	at scala.collection.immutable.List.map(List.scala:290)
	at com.github.simplesteph.ksm.parser.CsvAclParser.aclsFromReader(CsvAclParser.scala:81)
	at com.github.simplesteph.ksm.source.FileSourceAcl.refresh(FileSourceAcl.scala:34)
	at com.github.simplesteph.ksm.AclSynchronizer.$anonfun$run$1(AclSynchronizer.scala:76)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.simplesteph.ksm.AclSynchronizer.run(AclSynchronizer.scala:76)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$simplesteph$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:59)
	at com.github.simplesteph.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:13)
	at com.github.simplesteph.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)
Caused by: kafka.common.KafkaException: Allow not a valid operation name. The valid names are Read,Write,Create,Delete,Alter,Describe,ClusterAction,AlterConfigs,DescribeConfigs,IdempotentWrite,All
	at kafka.security.auth.Operation$.$anonfun$fromString$2(Operation.scala:79)
	at scala.Option.getOrElse(Option.scala:138)
	at kafka.security.auth.Operation$.fromString(Operation.scala:79)
	at com.github.simplesteph.ksm.parser.CsvAclParser.parseRow(CsvAclParser.scala:46)
	at com.github.simplesteph.ksm.parser.CsvAclParser.$anonfun$aclsFromReader$3(CsvAclParser.scala:83)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.simplesteph.ksm.parser.CsvAclParser.$anonfun$aclsFromReader$2(CsvAclParser.scala:83)
	... 17 more
```

**Comment by simplesteph** [comment]
In what way is it not compatible today ?

**Comment by CurtisEppel** [comment]
I'm assuming the error is because the current Kafka client libraries are using 2.3.1. I have a PR to update them to 2.5.0

**Comment by simplesteph** [comment]
cool, so far this will do!
