### ISSUE TITLE
Connection Timeout when Using AUTHORIZER_CLASS com.github.simplesteph.ksm.compat.AdminClientAuthorizer

### ISSUE THREAD

**Issue by chieftecho** [simplesteph/kafka-security-manager#91]
Setup:
Install Zookeeper and Kafka .../dist/kafka/2.5.0/kafka_2.13-2.5.0.tgz
Configure Zookeeper with TLS on port 2181 and without TLS on port 2180
Configure Kafka with TLS, SASL and SCRAM on port 9093 (using Zookeeper on TLS port 2181)

this works:
docker run -it \
-e AUTHORIZER_ZOOKEEPER_CONNECT="zookeeper-test-01:2180,zookeeper-test-02:2180,zookeeper-test-03:2180" \
-e KSM_EXTRACT=true \
simplesteph/kafka-security-manager:latest

this doesn't work:
docker run -it \
-e AUTHORIZER_CLASS="com.github.simplesteph.ksm.compat.AdminClientAuthorizer" \
-e ADMIN_CLIENT_BOOTSTRAP_SERVERS="kafka-test-01:9093,kafka-test-02:9093,kafka-test-03:9093" \
-e ADMIN_CLIENT_SECURITY_PROTOCOL="SASL_SSL" \
-e ADMIN_CLIENT_SASL_JAAS_CONFIG="org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user\" password=\"very-secret\";" \
-e ADMIN_CLIENT_SASL_MECHANISM="SCRAM-SHA-512" \
-e ADMIN_CLIENT_SSL_KEY_PASSWORD="" \
-e ADMIN_CLIENT_SSL_KEYSTORE_LOCATION="/cacerts" \
-e ADMIN_CLIENT_SSL_KEYSTORE_PASSWORD="secret" \
-e ADMIN_CLIENT_SSL_TRUSTSTORE_LOCATION="/cacerts" \
-e ADMIN_CLIENT_SSL_TRUSTSTORE_PASSWORD="secret" \
-e KSM_EXTRACT=true \
-v /cacerts:/cacerts \
simplesteph/kafka-security-manager:latest

Output:
[2020-09-02 13:34:25,462] INFO AdminClientConfig values: 
	bootstrap.servers = [kafka-test-01:9093, kafka-test-02:9093, kafka-test-03:9093]
	client.dns.lookup = default
	client.id = kafka-security-manager
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = SCRAM-SHA-512
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = [hidden]
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = /cacerts
	ssl.keystore.password = [hidden]
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.2
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = /cacerts
	ssl.truststore.password = [hidden]
	ssl.truststore.type = JKS
 (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,724] INFO Successfully logged in. (org.apache.kafka.common.security.authenticator.AbstractLogin)
[2020-09-02 13:34:25,950] WARN The configuration 'ssl.truststore.location' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,950] WARN The configuration 'ssl.keystore.password' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,950] WARN The configuration 'ssl.key.password' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,950] WARN The configuration 'sasl.jaas.config' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,950] WARN The configuration 'ssl.keystore.location' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,950] WARN The configuration 'ssl.truststore.password' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
[2020-09-02 13:34:25,952] INFO Kafka version: 2.5.0 (org.apache.kafka.common.utils.AppInfoParser)
[2020-09-02 13:34:25,952] INFO Kafka commitId: 66563e712b0b9f84 (org.apache.kafka.common.utils.AppInfoParser)
[2020-09-02 13:34:25,952] INFO Kafka startTimeMs: 1599053665950 (org.apache.kafka.common.utils.AppInfoParser)
[2020-09-02 13:34:25,955] INFO Running ACL Extraction mode (ExtractAcl)
[2020-09-02 13:34:25,955] INFO Getting ACLs from Kafka (ExtractAcl)
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeAcls, deadlineMs=1599053725975) timed out at 1599053725977 after 1 attempt(s)
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.github.simplesteph.ksm.compat.AdminClientAuthorizerBase.getAcls(AdminClientAuthorizer.scala:62)
	at com.github.simplesteph.ksm.compat.AdminClientAuthorizerBase.getAcls$(AdminClientAuthorizer.scala:60)
	at com.github.simplesteph.ksm.compat.AdminClientAuthorizer.getAcls(AdminClientAuthorizer.scala:90)
	at com.github.simplesteph.ksm.ExtractAcl.extract(ExtractAcl.scala:14)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$simplesteph$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:32)
	at com.github.simplesteph.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:18)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.github.simplesteph.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:18)
	at com.github.simplesteph.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeAcls, deadlineMs=1599053725975) timed out at 1599053725977 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

Is this a Kafka 2.5 incompatibility problem?

BTW I guess connection and authentication works, because when I provide invalid SASL credentials I get this in the kafka-logs:
[2020-09-02 14:39:51,561] INFO [SocketServer brokerId=0] Failed authentication with 10.xx.xx.xx/10.xx.xx.xx (Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512) (org.apache.kafka.common.network.Selector)
Sep  2 14:39:51 kafka-test-01 kafka-server-start.sh[41748]: [2020-09-02 14:39:51,561] INFO [SocketServer brokerId=0] Failed authentication with 10.xx.xx.xx/10.xx.xx.xx (Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512) (org.apache.kafka.common.network.Selector)

**Comment by chieftecho** [comment]
Found the reason:
I added the user "user" to the super user list with a comma and not with a semicolon:
wrong: super.users=User:admin,User:user
correct: super.users=User:admin;User:user

Now it works even with Kafka version 2.5!
